### ISSUE TITLE
Level up issues

### ISSUE THREAD

**Issue by Tyberius2303** [ceriath/candelafvtt#4]
Currently, I don't believe there are any options to add on circle or class-level options.
The group I am with have been playing since the first launch and has levelled once.
I managed to get around the characters drives etc by editing the class file but found no way to increase the circles resources except by adding another member.

**Comment by ceriath** [comment]
Hi there!
Thank you for using the system :)
Yes, level ups are indeed not really supported at the moment. I aimed to release something that people can start using it for now.
I hopefully get that added some time during next week.
Sorry for the inconvenience!

**Comment by Tyberius2303** [comment]
Ah no inconvenience! 
Thank you for putting it up on Foundry, makes it handy for the game!
Works amazingly well otherwise so keep up the good work!

**Comment by ceriath** [comment]
I think this is a solved issue.
Advancing circles grants a new circle ability, which is possible
Advancing character gives these options:
- add 1 action point: this has been possible from the beginning
- add 2 drive points: this has been fixed in #3 
- take a new ability: this has been possible from the beginning
- gild an additional action: this has been possible from the beginngin

If there are any things i missed, please let me know!
Cheers
